---
title             : "Unravelling the time-course of listener adaptation to an unfamiliar talker"
shorttitle        : "short article draft"
date              : "`r format(Sys.time(), '%B %d, %Y')`"

author: 
  - name          : "Maryann Tan"
    affiliation   : "1, 2"
    corresponding : yes    # Define only one corresponding author
    address       : "Department of Bilingualism, Stockholm University, Sweden"
    email         : "maryann.tan@biling.su.se"
  - name          : "T. Florian Jaeger"
    affiliation   : "2,3"

affiliation:
  - id            : "1"
    institution   : "Centre for Research on Bilingualism, University of Stockholm"
  - id            : "2"
    institution   : "Brain and Cognitive Sciences, University of Rochester"
  - id            : "3"
    institution   : "Computer Science, University of Rochester"

authornote: |
  We are grateful to ### ommitted for review ###


abstract: |
  YOUR ABSTRACT GOES HERE. All data and code for this study are shared via OSF, including the R markdown document that this article is generated from, and an R library that implements the models we present.
  
keywords          : "speech perception; adaptation; incremental changes; distributional learning"
wordcount         : "X"

bibliography      : ["latex-stuff/library.bib", "latex-stuff/r-references.bib"]
link-citations    : yes
csl               : latex-stuff/apa-6th-edition.csl

floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
numbersections    : true
mask              : no
draft             : no

header-includes: 
 - \usepackage{sectsty}
 - \usepackage{animate}
 - \usepackage{amsmath}
 - \usepackage{tikz}
 - \usetikzlibrary{bayesnet}
 - \usepackage{booktabs}
 - \usepackage{siunitx}
 - \usepackage{soul}
 - \usepackage{tabto}
 - \usepackage{xcolor}
 - \usepackage{placeins}
 - \setstcolor{red}
 - \sectionfont{\color{black}}
 - \subsectionfont{\color{black}}
 - \subsubsectionfont{\color{black}}
 - \usepackage{setspace}\doublespacing
 - \usepackage{subfig} 
 - \usepackage{lscape}
 - \usepackage{pdflscape}
 
documentclass     : "apa6"
classoption       : "man"
fontsize          : 11pt
output: 
  papaja::apa6_pdf:
    latex_engine: xelatex
    extra_dependencies: "subfig" 
    includes:
      in_header: latex-stuff/header.tex
always_allow_html: true
---

\setcounter{secnumdepth}{5}

```{r libraries, include=FALSE, message=FALSE}
# If installation of remote libraries is necessary, uncomment this code:
# library(curl)               # Check availability of internet for install of remote libraries
# if(!requireNamespace("remotes", quietly = TRUE)) if (has_internet()) install.packages("remotes")
# if (has_internet()) remotes::install_github("crsh/papaja")
# if (has_internet()) remotes::install_github("hlplab/MVBeliefUpdatr")
# if (has_internet()) remotes::install_github('kleinschmidt/phonetic-sup-unsup')

library(papaja)             # APA formatted ms

library(MASS)               # sliding difference coding (load before tidyverse b/c of select-conflict)
library(tidyverse)          # keeping things tidy
library(magrittr)           # pipes
library(rlang)              # quosures (in functions)
library(assertthat)         # asserts (in functions)

library(patchwork)          # plot layouts  
library(magick)
library(webshot)
library(ggstance)
library(ggtext)            # make geom textboxes
library(ggnewscale)        # extra colour scale in ggplots
library(kableExtra)        # for formatting tables

library(linguisticsdown)    # IPA symbols
library(latexdiffr)         # track changes

library(lme4)               # c-CuRE fn and cue adjustments
library(brms)               # fit Bayesian regression models
library(tidybayes)          # posterior samples and plots in tidy format
library(broom.mixed)        # extracting effects from lmer models
library(posterior)

library(phonR)              # normalization of f0
library(supunsup)           # Kleinschmidt & Jaeger 2016 data
library(MVBeliefUpdatr)     # generating Ideal Observers
```


```{r constants-general, include=FALSE}
# IF you're using brms or rstan, uncomment the following:
chains <- 4
options(
  width = 1000,
  mc.cores = min(chains, parallel::detectCores()))

# plot formatting
colours.voicing <- c("#7EC8E3", "#990033")
colours.sex <- c("#c1502e", "#2F9FC2")
remove_all_axes <- 
  theme(axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
remove_axes_titles <- 
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank())
remove_x_guides <- 
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank())
```


```{r functions-general, include=FALSE}
source("functions.R")

# For plotting
myGplot.defaults("paper")

# Get citation information
r_refs(file = "latex-stuff/r-references.bib")
```


```{r knitr-setup, include=FALSE}
# To keep figure sizes comparable across the paper, you can define a basic width and height (e.g., for each panel)
# and then refer to those variables in the knitr chunk options that describe the figure width and height for a 
# specific R chunk.
options(width = 200, digits = 2, OutDec = ".", tinytex.verbose = TRUE)
base.width = 1.75
base.height = 1.75

knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE, 
  results = "markup", cache = TRUE,
  interval = .2,
  fig.align = "center", fig.height = base.height, fig.width = base.width)

# Some useful formatting for warnings and error messages, so that they are not easily missed.
knitr::knit_hooks$set(inline = function(x) { 
  prettyNum(x, big.mark=",") })
knitr::knit_hooks$set(document = function(x) {
  sub('\\usepackage[]{color}', '\\usepackage{xcolor}', x, fixed = TRUE)})
color_block = function(color) { 
  function(x, options) sprintf('\\color{%s}\\begin{verbatim}%s\\end{verbatim}\\color{black}', color, x) }
knitr::knit_hooks$set(error = color_block('red'))
knitr::knit_hooks$set(warning = color_block('orange'))

animate = T         # switch on/off to replace animations with facets (not yet implemented for all instances)
TODO = T            # switch on/off to get to do list.
RESET_FIGURES = F   # switch on/off whether figures that exist as files are regenerated
```


```{r analysis-preferences}
set.seed(42007)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```


```{r, child="section-0-TO-DO.Rmd", eval= if (TODO) TRUE else FALSE}
```

\newpage 
\setcounter{page}{1}
\setcounter{section}{0}

```{r, child="section-1-introduction.Rmd"}
```

```{r, child="section-2-methods.Rmd"}
```

```{r, child="section-3-results-analysis.Rmd"}
```

```{r, child="section-4-general-discussion.Rmd"}
```

```{r child="section-5-references.Rmd"}
```

\newpage
\setcounter{page}{1}
\renewcommand{\thesection}{\S \arabic{section}}
\renewcommand{\theHsection}{sisection. \arabic{section}}

```{r, child="supplementary-information.Rmd", eval=FALSE}
```

