---
title: "adapted-plots-for-conference-presentations"
author: "Maryann Tan"
date: "2023-01-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document is for modifying plots from the article for other forms of presentations (e.g. conference posters). Should be opened together with the main article documents (AEDLVOT sections) where the plots are generated

```{r temporary-chunk-poster-plotting, warning=FALSE, fig.height=1.5, fig.width=3}
p1 <-
  p.IOs.VOT.no.noise +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        plot.margin = unit(c(1, 0, 0, 0), "cm"))
p2 <-
  p.IOs.VOT +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.margin = unit(c(1, 0.5, 0, 0), "cm"))
p3 <-
  p.IOs.VOT_F0 +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.margin = unit(c(1, 0.5, 0, 0), "cm"))
p4 <-
  p.IOs.VOT_F0.centered +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.margin = unit(c(1, 0.5, 0, 0), "cm"))

p5 <-
  p.IOs.VOT_F0.centered.input +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        plot.margin = unit(c(1, 0.5, 0, 0), "cm"))

legend <- get_legend(p.IOs.VOT_F0 + theme(legend.position = "top"))


IO_grid1 <- plot_grid(p2, p3, p4, p5,
    ncol = 4,
    align = "h",
    labels = c("VOT (+perceptual noise)", 
               "VOT-F0", 
               "VOT-F0 (+talker-centered)", 
               "VOT-F0 (+exposure-centered)"),
    label_size = 6,
    label_y = 0.86,
    hjust = 0,
    vjust = 0)

IO_grid2 <- plot_grid(
  p1, IO_grid1,
  ncol = 2,
  align = "v",
  labels = c("VOT", ""),
  label_y = 0.88,
  label_x = 0.25,
  hjust = 0,
  vjust = 1,
  label_size = 6,
  rel_widths = c(0.26, 1)
)


IO_grid2 <- add_sub(IO_grid2, "VOT (msec)", x = .55, size = 10, fontface = "bold", vjust = 0)
#IO_grid1 <- add_sub(IO_grid1, "Proportion of 't'-responses", x = -0.03, y = 0, size = 10, fontface = "bold", angle = 90)

p <- ggdraw(IO_grid2)
p
leg <- ggdraw(legend)
ggsave("../figures/IO_plot_exp1.png", plot = p, width = 9, height = 2.2, units = "in", dpi = 300)
```


```{r, fig.width=6, fig.height=3}
# plot median likelihood per response with bootstrapped 95% CI
d.test.IO %>% 
  group_by(io.type) %>% 
  summarise(
    median_likelihood_per_response = median(likelihood_per_response)) %>%
  mutate(io.type = fct_relevel(io.type, levels = c("VOT.no.noise", "VOT", "VOT_F0", "VOT_F0.centered",  "VOT_F0.centered.input"))) %>% 
  ggplot(aes(x = io.type, 
             y = median_likelihood_per_response)) +
  geom_point(size = 2, colour = "#333333", alpha = .8) +
  geom_errorbar(
    data = d.bootstrap %>% 
      group_by(io.type) %>% 
      mutate(io.type = fct_relevel(io.type, levels = c("VOT.no.noise", "VOT", "VOT_F0", "VOT_F0.centered",  "VOT_F0.centered.input"))) %>% 
      summarise(
        median.lower = quantile(median_sample, probs = .025),
        median.upper = quantile(median_sample, probs = .975)
      ),
    mapping = 
      aes(x = io.type, ymin = median.lower, ymax = median.upper),
    colour = "#333333",
    size = 1.5,
    alpha = .6,
    width = 0,
    inherit.aes = F) +
  scale_y_continuous("Median likelihood per response") +
   scale_x_discrete( 
     limits = c("VOT.no.noise", "VOT", "VOT_F0", "VOT_F0.centered", "VOT_F0.centered.input"),
     breaks = c("VOT.no.noise", "VOT", "VOT_F0", "VOT_F0.centered", "VOT_F0.centered.input"),
     labels = c(VOT.no.noise = "VOT", VOT = "VOT\n(+perceptual noise)", VOT_F0 = "VOT-F0\n", VOT_F0.centered = "VOT-F0\n (+talker centered)", VOT_F0.centered.input = "VOT-F0 \n (+exposure-centered)")) +
  theme(axis.title.x = element_blank(),
        legend.position = "none") +
  guides(x = guide_axis(angle = 45)) +
  coord_trans(y = "log10")

ggsave("~/Desktop/plot_fig5.png", plot = last_plot(), 
       width = 3.5, height = 4, units = "in", dpi = 300)
```



```{r zoom-in-upper, fig-width=2}
d.test.IO %>% 
  group_by(io.type) %>% 
  summarise(
    median_likelihood_per_response = median(likelihood_per_response),
    mode_likelihood_per_response = max(likelihood_per_response)) %>%
  mutate(io.type = fct_relevel(io.type, levels = c("VOT.no.noise", "VOT", "VOT_F0", "VOT_F0.centered",  "VOT_F0.centered.input"))) %>%
  ggplot(aes(x = io.type, 
             y = median_likelihood_per_response)) +
  geom_point(size = 3,
             colour = "#333333") +
  geom_point(aes(x = io.type, 
                 y = mode_likelihood_per_response), 
             size = 3, 
             shape = 17,
             colour = "#333333") +
  geom_errorbar(
    data = d.bootstrap %>% 
      group_by(io.type) %>%
  mutate(io.type = fct_relevel(io.type, levels = c("VOT.no.noise", "VOT", "VOT_F0", "VOT_F0.centered",  "VOT_F0.centered.input"))) %>% 
      summarise(
        median.lower = quantile(median_sample, probs = .025),
        median.upper = quantile(median_sample, probs = .975)
      ),
    mapping = 
      aes(x = io.type, ymin = median.lower, ymax = median.upper),
    colour = "#333333",
    size = 1.5,
    alpha = .6,
  width = 0,
    inherit.aes = F) + 
    geom_errorbar(
    data = d.bootstrap %>% 
      group_by(io.type) %>%
  mutate(io.type = fct_relevel(io.type, levels = c("VOT.no.noise", "VOT", "VOT_F0", "VOT_F0.centered",  "VOT_F0.centered.input"))) %>% 
      summarise(
        mode.lower = quantile(mode_sample, probs = .025),
        mode.upper = quantile(mode_sample, probs = .975)
      ),
    mapping = 
      aes(x = io.type, ymin = mode.lower, ymax = mode.upper),
    colour = "#333333",
    size = 1.5,
    alpha = .6,
  width = 0,
    inherit.aes = F) +
  scale_y_continuous("Median log-likelihood \n per response", limits = c(.554, .67)) +
  scale_x_discrete(expand = expansion(mult = c(0.09, 0.09)), 
                   limits = c("VOT_F0", "VOT_F0.centered", "VOT_F0.centered.input"),
                   breaks = c("VOT_F0", "VOT_F0.centered", "VOT_F0.centered.input"),
                   labels = c(VOT_F0 = "VOT-F0\n", VOT_F0.centered = "VOT-F0\n (talker centered)", VOT_F0.centered.input = "VOT-F0 \n (exposure-centered)")) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        legend.position = "none") +
  guides(x = guide_axis(angle = 45)) +
  coord_trans(y = "log10") 

ggsave("~/Desktop/plot_fig5b.png", plot = last_plot(), 
       width = 2.5, height = 3, units = "in", dpi = 300)
```